Feature/dev 53 - Sending available tracks and options
kaczkadevteam/harmonify-api pull request #9
Opened 2024-05-07 09:10 UTC by radkam2000

2024-05-07 11:40 UTC, MarcinSkic requested changes
Brak znaczących błędów w logice, głównie nazewnictwo do zmiany

2024-05-07 11:40 UTC, MarcinSkic commented on Models/Messages/MessageType.cs
> +  DataTooLarge,
Powinien być pod nagłówkiem ERRORS

2024-05-07 11:40 UTC, MarcinSkic commented on Helpers/PolymorphicTypeResolver.cs
> +        DerivedTypes =
Do dyskusji: typ mógłby zostać uczyniony bardziej przejrzystym tworząc syntax `type/generic`, idąc po kolei byłoby:
- `base`
- `error`
- `base/createdGameDto`
- `base/gameStartedDto`
- `base/string`
itd.

2024-05-07 11:40 UTC, MarcinSkic commented on Models/Track.cs
> +  public required string Guess { get; set; }
Guess albo nie będzie w tym obiekcie albo powinien być opcjonalny, on nie będzie przesyłany z frontu tylko backend będzie go generować

2024-05-07 11:40 UTC, MarcinSkic commented on Models/Track.cs
> +  public required int TrackStart_ms { get; set; }
To też raczej będzie na backendzie ustawiane

2024-05-07 11:40 UTC, MarcinSkic commented on Services/WebSocketReceiverService.cs
> +using System.Text.Json;
Nie używany import

2024-05-07 11:40 UTC, MarcinSkic commented on Helpers/PolymorphicTypeResolver.cs
> +          new JsonDerivedType(typeof(MessageWithData<StartedGameDto>), "gameStartedDto"),
Typ się nazywa `StartedGameDto` a string `gameStartedDto`, usystematyzować

2024-05-07 15:40 UTC, radkam2000 commented on Helpers/PolymorphicTypeResolver.cs
> +        DerivedTypes =
W sumie to nie jest zły pomysł

2024-05-07 15:55 UTC, radkam2000 commented on Helpers/PolymorphicTypeResolver.cs
> +          new JsonDerivedType(typeof(MessageWithData<StartedGameDto>), "gameStartedDto"),
A no tak bo zmieniłem zmienną i strina nie wykryło

2024-05-08 08:27 UTC, MarcinSkic approved these changes

2024-05-08 08:27 UTC, merged